[versions]
quarkus = "3.30.0"
zeroconf = "1.3.2"

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }

[libraries]
quarkus-bom = { group = "io.quarkus", name="quarkus-bom", version.ref = "quarkus" }
zeroconf = { group = "xyz.gianlu.zeroconf", name="zeroconf", version.ref="zeroconf" }
